### ISSUE TITLE
How is memory used?

### ISSUE THREAD

**Issue by jdonkers** [Torantulino/Auto-GPT#254]
Are memories ever retrieved and used again in the future? I'm looking at the code and can't tell if they are integrated (and if they are how it works). The prompt lists only: add, delete, and overwrite.

**Comment by jdonkers** [comment]
I have the same issue. Several times Auto-GPT searched the same topic then put it in memory.

**Comment by rogeriosmorais** [comment]
Every time you ping GPT the permanent memory is added to the conversation. So it doesn't require a explicit command to read memory because it's always reading it.

![image](https://user-images.githubusercontent.com/28842513/230156261-cb68c58d-cf9f-4770-a2ea-01c2dade43f6.png)

Is that the most efficient way of handling it? I have no idea, but the memory is definitely being used.

**Comment by jdonkers** [comment]
Thank you [rogeriosmorais](https://github.com/rogeriosmorais), that makes sense. Looking closer at chat.py, it appears only the message history is pruned, and not the permanent memory.

GPT, speaking on this file:

> The code provided does not specifically prune the permanent memory if it doesn't fit within the token limit. Instead, it builds the current context by reserving tokens for the system prompt, permanent memory, and user input. Then, it iteratively adds messages from the full message history to the current context until it reaches the token limit. However, if the length of the permanent memory is too large and doesn't leave enough tokens for a proper conversation, you could face issues with the code.

**Comment by dschonholtz** [comment]
Please see PR #122 for an overview of memory and how it is likely to change
