### ISSUE TITLE
Unable to run speak.py

### ISSUE THREAD

**Issue by thenetguy** [Torantulino/Auto-GPT#262]
I'm doing this on Windows 11 WSL when I run speak.py it says. 
`playsound is relying on another python subprocess. Please use pip install pygobject if you want playsound to run more efficiently.`
when I run pip install pygobject , it says 
`Requirement already satisfied: pygobject in /usr/lib/python3/dist-packages (3.42.1)
Requirement already satisfied: pycairo>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from pygobject) (1.23.0)`
not sure what I'm doing wrong , I can run main.py and it works.

**Comment by ArchEight** [comment]
I can suggest a few potential resolutions for you to try:

Update the playsound library: Ensure that the playsound library is up to date by running the following command:

pip install --upgrade playsound
This ensures that the latest version of the library is installed, which may fix the issue.

Install PyGObject for Python 3: Instead of using the system package manager to install pygobject, try installing it using pip for Python 3:

pip3 install PyGObject
This will ensure that the package is installed for the correct Python version and might resolve the subprocess warning.

Use the platform-specific version of playsound: If the issue persists, consider using a platform-specific version of the playsound library. For Windows, you can try using the winsound library that comes with Python. Replace the playsound function calls in the speak.py script with the following code:

import winsound

def play_sound(file_path):
    winsound.PlaySound(file_path, winsound.SND_FILENAME)
Replace the existing playsound function calls with play_sound function calls, passing the same file path parameter.

Note that this solution is specific to the Windows platform and may not work on other operating systems.

**Comment by jdrusso** [comment]
I was having lots of issues with `playsound`, so I just patched it to use `pygame`.

See https://github.com/jdrusso/Auto-GPT/commit/d70f5eca8151e1f4e159138863fb2ef9eb73271f
