### ISSUE TITLE
Best way to update AutoGPT 

### ISSUE THREAD

**Issue by sjnt1** [Torantulino/Auto-GPT#842]
Hello! Tech newb here. 

Downloaded Auto-GPT trough zip file and have been having a blast. I'm just recently back on a computer after using console and smartphone for forever, so excuse me for the stupid question: 

What's the best and easiest way to update Auto-GPT and incorporate the latest updates on this site?

**Comment by crimson-knight** [comment]
If you haven't already, install `git` and it's cli tools.

Then clone the repo to your local machine instead of downloading from a zip file. Look up a tutorial on it, they are everywhere.

When you want updates that have been made to master, run `git pull`. Just beware that any files you've made changes to that are part of the system will be overridden.

**Comment by richbeales** [comment]
We will be implementing 'releases' soon.  Are you happy for me to close this?

**Comment by sjnt1** [comment]
By all means im new to this.

**Comment by guyjabs** [comment]
Can you please elaborate on the update process? I have little tech experience so I'd appreciate clear instructions.

**Comment by ntindle** [comment]
Copy your .env somewhere you can reference like your desktop. Delete the folder of the tool and start the install instructions from scratch.
