### ISSUE TITLE
API Rate Limit Reached. Waiting 10 seconds...

### ISSUE THREAD

**Issue by ParvizSultonboev** [Torantulino/Auto-GPT#886]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I'm sure I spelled everything out correctly, but I get an eternal attempt to connect the api every 10 seconds after starting programm
`python3 main.py` and also `python3 main.py --continuous`

p.s. I have already downloaded and updated the file chat.py with last fix

### Current behavior 😯

Using memory of type: LocalCache
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...
Error:  API Rate Limit Reached. Waiting 10 seconds...

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by ChaosBeing** [comment]
Sounds like something that happened to me, so I'm going to work on the assumption your issue is the same.
This is an issue with OpenAI's API system. Specifically, OpenAI seems to allow for the creation of API keys for free accounts, but doesn't actually allow you to *use* them. You must add a payment method, then generate a new API key.
You don't need to sign up for Plus or anything, but the API *will* charge you a very small amount.

**Comment by MoElaSec** [comment]
@variety754 going thru the same issue even thou i have credits and also added my card (and added extra 5$ just in case) keep getting the same issue. this needs to be investigated further.

**Comment by ARKA1112** [comment]
I second this. I have created a simple flask  [app](https://github.com/ARKA1112/Chatgpt_with_flask) takes a prompt and returns an image using my personal OpenAI API key. Works flawlessly.
