### ISSUE TITLE
Save Long-Term-Memory to file on shutdown

### ISSUE THREAD

**Issue by Torantulino** [Torantulino/Auto-GPT#9]
Implement Save/Load of long-term memory to fine to enable continuation between instances.

Could optionally save current context too.

Note, this would have to be cleared if the user wanted to change Auto-GPT's task.

**Comment by Taytay** [comment]
In #45, I added a small yml file that saves some things off. I think we could have a separate folder (or docker container?) where all of this was stored:
name, goals, long term memory, etc.

Then, on startup, it would load that folder, which would contain all of the config, as well as its "file scratch pad" (or maybe docker container scratch pad?) so that it could pick up where it left off

**Comment by dschonholtz** [comment]
See pull #122 for a small wrinkle with respect to this. 
Saving and exporting an entire pinecone DB might be difficult

**Comment by Torantulino** [comment]
Fixed in #372
