### ISSUE TITLE
Command memory_ovr returned: Error: invalid literal for int() with base 10: 'clariontech_blog'

### ISSUE THREAD

**Issue by rajivpoddar** [Torantulino/Auto-GPT#90]

**Comment by Josedapker** [comment]
I had a similar error but I think I was able to fix it by asking chatGPT with some of the pertaining code:

Thanks for providing the code. The issue appears to be related to the use of int(key) in the overwrite_memory() function. The error occurs because you are trying to convert the key to an integer, but the value passed in as the argument is a string ('yelp_api_library').

To fix this issue, you should ensure that the value passed as the key argument is a valid integer. You can check if the value is a valid integer using the following method:

def is_valid_int(value):
    try:
        int(value)
        return True
    except ValueError:
        return False

def overwrite_memory(key, string):
    if is_valid_int(key) and 0 <= int(key) < len(mem.permanent_memory):
        _text = "Overwriting memory with key " + \
            str(key) + " and string " + string
        mem.permanent_memory[int(key)] = string
        print(_text)
        return _text
    else:
        print("Invalid key, cannot overwrite memory.")
        return None
This should prevent the error from occurring by only allowing valid integers to be used as keys in the overwrite_memory() function. However, you should also verify that the correct key is being passed to the function when it's called. If it's not, you may need to investigate other parts of your code to ensure that the correct value is being used as the key argument.

**Comment by ug02fast** [comment]
@slavakurilyak Seems to have worked for me 👍

**Comment by slavakurilyak** [comment]
See pull request https://github.com/Torantulino/Auto-GPT/pull/208

**Comment by gannonh** [comment]
Can't this be fixed just by using the the isinstance() function to check if the key argument is an instance of the int class before calling int() function?

`def overwrite_memory(key, string):
    if isinstance(key, int) and key >= 0 and key < len(mem.permanent_memory):
        _text = "Overwriting memory with key " + \
            str(key) + " and string " + string
        mem.permanent_memory[key] = string
        print(_text)
        return _text
    else:
        print("Invalid key, cannot overwrite memory.")
        return None`

**Comment by shafty023** [comment]
I am running these changes and still experiencing the same error. 

`SYSTEM:  Command message_agent returned: Error: invalid literal for int() with base 10: 'gpt_agent'`

**Comment by shafty023** [comment]
The following would be a better fix:

```
def is_valid_int(value):
    if isinstance(value, int):
        return True
    elif isinstance(value, str) and value.isdigit():
        return True
    else:
        return False
```

**Comment by zaabi1995** [comment]
how do i fix it
