### ISSUE TITLE
.

### ISSUE THREAD

**Issue by james-coder** [Torantulino/Auto-GPT#919]
.

**Comment by onekum** [comment]
It would be cool, but the implications of this are complex. I think the AI would probably need edit access to its local source code to implement a lot of commands, which is dangerous because it can just remove any safety features placed on it.

Anyway, bash shell access is probably going to be implemented soon anyway. It doesn't need more commands if it can just write and execute scripts within its workspace; it's practically the same thing.

**Comment by james431987** [comment]
How difficult would it be to implement giving agents read/write capabilities? My director is always trying to delegate tasks to agents but they just don't have the capability.

**Comment by Anasomer7** [comment]
i had that same idea. to make it possible we have to implement plugin architecture so AI can access the code and implement new features easily.  But we have to change the whole code base. i am thinking of doing it as a seperate project using langchain.
